POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RVc2VyIiwiaWQiOiI2NjQ1YTZjMmNmMzA1NjAyMzAzNTA5NTciLCJpYXQiOjE3MTU4Nzk1OTYsImV4cCI6MTcxNTg4MzE5Nn0.0Q_cE9fnR_UAYD7XQneK7Td4yZ2UzUGc_RwDPU91lQE

{
  "title": "title",
  "author": "author",
  "url": "url",
  "likes":"3",
  "userId": "664389398cdae5ac0c0c9e24"
}
